// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from './routes/_app.tsx'
import * as $attachment from './routes/attachment.tsx'
import * as $AddToCartArea from './islands/AddToCartArea.tsx'
import * as $AddToCartAreaNew from './islands/AddToCartAreaNew.tsx'
import * as $AddToCartButton_vtex from './islands/AddToCartButton/vtex.tsx'
import * as $BannerCarouselJS from './islands/BannerCarouselJS.tsx'
import * as $BenefitsJS from './islands/BenefitsJS.tsx'
import * as $CTAFixoCustom from './islands/CTAFixoCustom.tsx'
import * as $CartItem from './islands/CartItem.tsx'
import * as $Header_Buttons from './islands/Header/Buttons.tsx'
import * as $Header_Cart_Cart from './islands/Header/Cart/Cart.tsx'
import * as $Header_Cart_common from './islands/Header/Cart/common.tsx'
import * as $Header_Cart_vtex from './islands/Header/Cart/vtex.tsx'
import * as $Header_Drawers from './islands/Header/Drawers.tsx'
import * as $Header_MyAccount from './islands/Header/MyAccount.tsx'
import * as $Header_Searchbar from './islands/Header/Searchbar.tsx'
import * as $Logger from './islands/Logger.tsx'
import * as $MicroHeaderSetup from './islands/MicroHeaderSetup.tsx'
import * as $NavbarWrapper from './islands/NavbarWrapper.tsx'
import * as $Newsletter from './islands/Newsletter.tsx'
import * as $OrderTracking from './islands/OrderTracking.tsx'
import * as $OutOfStock from './islands/OutOfStock.tsx'
import * as $PixPrice from './islands/PixPrice.tsx'
import * as $PixPriceNew from './islands/PixPriceNew.tsx'
import * as $PriceRange from './islands/PriceRange.tsx'
import * as $Product_Benefits from './islands/Product/Benefits.tsx'
import * as $Product_ImageSliderJS from './islands/Product/ImageSliderJS.tsx'
import * as $Product_ProductSimilars from './islands/Product/ProductSimilars.tsx'
import * as $Product_ProductStarCard from './islands/Product/ProductStarCard.tsx'
import * as $Product_SellingPrice from './islands/Product/SellingPrice.tsx'
import * as $Product_SellingPriceNew from './islands/Product/SellingPriceNew.tsx'
import * as $Product_SendEventOnViewIsland from './islands/Product/SendEventOnViewIsland.tsx'
import * as $Product_Trustvox from './islands/Product/Trustvox.tsx'
import * as $ProductCardBuy from './islands/ProductCardBuy.tsx'
import * as $ProductShelfWithImageJS from './islands/ProductShelfWithImageJS.tsx'
import * as $PromoCoupon from './islands/PromoCoupon.tsx'
import * as $PromotionsSection from './islands/PromotionsSection.tsx'
import * as $Radio from './islands/Radio.tsx'
import * as $ShippingSimulation from './islands/ShippingSimulation.tsx'
import * as $SliderJS from './islands/SliderJS.tsx'
import * as $Sort from './islands/Sort.tsx'
import * as $Stories from './islands/Stories.tsx'
import * as $Subscription from './islands/Subscription.tsx'
import * as $SubscriptionModal from './islands/SubscriptionModal.tsx'
import * as $VideoModal_Button from './islands/VideoModal/Button.tsx'
import * as $VideoModal_Modal from './islands/VideoModal/Modal.tsx'
import * as $WishlistButton_vtex from './islands/WishlistButton/vtex.tsx'
import type { Manifest } from '$fresh/server.ts'

const manifest = {
	routes: {
		'./routes/_app.tsx': $_app,
		'./routes/attachment.tsx': $attachment,
	},
	islands: {
		'./islands/AddToCartArea.tsx': $AddToCartArea,
		'./islands/AddToCartAreaNew.tsx': $AddToCartAreaNew,
		'./islands/AddToCartButton/vtex.tsx': $AddToCartButton_vtex,
		'./islands/BannerCarouselJS.tsx': $BannerCarouselJS,
		'./islands/BenefitsJS.tsx': $BenefitsJS,
		'./islands/CTAFixoCustom.tsx': $CTAFixoCustom,
		'./islands/CartItem.tsx': $CartItem,
		'./islands/Header/Buttons.tsx': $Header_Buttons,
		'./islands/Header/Cart/Cart.tsx': $Header_Cart_Cart,
		'./islands/Header/Cart/common.tsx': $Header_Cart_common,
		'./islands/Header/Cart/vtex.tsx': $Header_Cart_vtex,
		'./islands/Header/Drawers.tsx': $Header_Drawers,
		'./islands/Header/MyAccount.tsx': $Header_MyAccount,
		'./islands/Header/Searchbar.tsx': $Header_Searchbar,
		'./islands/Logger.tsx': $Logger,
		'./islands/MicroHeaderSetup.tsx': $MicroHeaderSetup,
		'./islands/NavbarWrapper.tsx': $NavbarWrapper,
		'./islands/Newsletter.tsx': $Newsletter,
		'./islands/OrderTracking.tsx': $OrderTracking,
		'./islands/OutOfStock.tsx': $OutOfStock,
		'./islands/PixPrice.tsx': $PixPrice,
		'./islands/PixPriceNew.tsx': $PixPriceNew,
		'./islands/PriceRange.tsx': $PriceRange,
		'./islands/Product/Benefits.tsx': $Product_Benefits,
		'./islands/Product/ImageSliderJS.tsx': $Product_ImageSliderJS,
		'./islands/Product/ProductSimilars.tsx': $Product_ProductSimilars,
		'./islands/Product/ProductStarCard.tsx': $Product_ProductStarCard,
		'./islands/Product/SellingPrice.tsx': $Product_SellingPrice,
		'./islands/Product/SellingPriceNew.tsx': $Product_SellingPriceNew,
		'./islands/Product/SendEventOnViewIsland.tsx': $Product_SendEventOnViewIsland,
		'./islands/Product/Trustvox.tsx': $Product_Trustvox,
		'./islands/ProductCardBuy.tsx': $ProductCardBuy,
		'./islands/ProductShelfWithImageJS.tsx': $ProductShelfWithImageJS,
		'./islands/PromoCoupon.tsx': $PromoCoupon,
		'./islands/PromotionsSection.tsx': $PromotionsSection,
		'./islands/Radio.tsx': $Radio,
		'./islands/ShippingSimulation.tsx': $ShippingSimulation,
		'./islands/SliderJS.tsx': $SliderJS,
		'./islands/Sort.tsx': $Sort,
		'./islands/Stories.tsx': $Stories,
		'./islands/Subscription.tsx': $Subscription,
		'./islands/SubscriptionModal.tsx': $SubscriptionModal,
		'./islands/VideoModal/Button.tsx': $VideoModal_Button,
		'./islands/VideoModal/Modal.tsx': $VideoModal_Modal,
		'./islands/WishlistButton/vtex.tsx': $WishlistButton_vtex,
	},
	baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
