// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from './apps/decohub.ts'
import * as $$$$$$$$$$$1 from './apps/site.ts'
import * as $$$2 from './loaders/availableIcons.ts'
import * as $$$3 from './loaders/centralNavigation.ts'
import * as $$$0 from './loaders/CustomPLPTitle.ts'
import * as $$$1 from './loaders/PLPSectionsSEO.ts'
import * as $$$4 from './loaders/seals.tsx'
import * as $$$$$$$0 from './matchers/canonical.ts'
import * as $$$$$$0 from './sections/Category/CategoryBanner.tsx'
import * as $$$$$$1 from './sections/Category/CategoryCarousel.tsx'
import * as $$$$$$2 from './sections/Category/CategoryGrid.tsx'
import * as $$$$$$3 from './sections/Category/CategoryGridCircle.tsx'
import * as $$$$$$4 from './sections/Category/CategoryList.tsx'
import * as $$$$$$5 from './sections/Content/Benefits.tsx'
import * as $$$$$$6 from './sections/Content/BlogPosts.tsx'
import * as $$$$$$7 from './sections/Content/CallToAction.tsx'
import * as $$$$$$8 from './sections/Content/CardsSlider.tsx'
import * as $$$$$$9 from './sections/Content/CardsWithCta.tsx'
import * as $$$$$$10 from './sections/Content/CardsWithImageCta.tsx'
import * as $$$$$$11 from './sections/Content/DescriptionWithCta.tsx'
import * as $$$$$$12 from './sections/Content/Faq.tsx'
import * as $$$$$$13 from './sections/Content/Features.tsx'
import * as $$$$$$14 from './sections/Content/Hero.tsx'
import * as $$$$$$15 from './sections/Content/HighlightsBanner.tsx'
import * as $$$$$$16 from './sections/Content/ImageSection.tsx'
import * as $$$$$$17 from './sections/Content/Logos.tsx'
import * as $$$$$$18 from './sections/Content/RenderHTMLBlock.tsx'
import * as $$$$$$19 from './sections/Content/RichText.tsx'
import * as $$$$$$20 from './sections/Content/TextAndBanner.tsx'
import * as $$$$$$21 from './sections/Content/VideoModal.tsx'
import * as $$$$$$22 from './sections/Footer/Footer.tsx'
import * as $$$$$$23 from './sections/Gallery.tsx'
import * as $$$$$$24 from './sections/Header/Header.tsx'
import * as $$$$$$25 from './sections/Images/AccordionWithImages.tsx'
import * as $$$$$$26 from './sections/Images/BannerImage.tsx'
import * as $$$$$$27 from './sections/Images/BannerInfo.tsx'
import * as $$$$$$28 from './sections/Images/BannerInfoContainer.tsx'
import * as $$$$$$29 from './sections/Images/BannerInfoVideo.tsx'
import * as $$$$$$30 from './sections/Images/BannerInfoWithDivider.tsx'
import * as $$$$$$31 from './sections/Images/BannerInfoWithItems.tsx'
import * as $$$$$$32 from './sections/Images/Carousel.tsx'
import * as $$$$$$33 from './sections/Images/ImageGallery.tsx'
import * as $$$$$$34 from './sections/Images/ImageGrid.tsx'
import * as $$$$$$35 from './sections/Images/ShoppableBanner.tsx'
import * as $$$$$$36 from './sections/Insider/InsiderTracking.tsx'
import * as $$$$$$37 from './sections/Insider/OrderTracking.tsx'
import * as $$$$$$38 from './sections/Insider/types.ts'
import * as $$$$$$39 from './sections/Links/Shortcuts.tsx'
import * as $$$$$$40 from './sections/Miscellaneous/CampaignTimer.tsx'
import * as $$$$$$41 from './sections/Miscellaneous/CookieConsent.tsx'
import * as $$$$$$42 from './sections/Miscellaneous/FloatingButtons.tsx'
import * as $$$$$$43 from './sections/Miscellaneous/Slide.tsx'
import * as $$$$$$44 from './sections/Miscellaneous/Space.tsx'
import * as $$$$$$45 from './sections/Newsletter/Newsletter.tsx'
import * as $$$$$$46 from './sections/Product/Description.tsx'
import * as $$$$$$47 from './sections/Product/ImageGalleryFrontBack.tsx'
import * as $$$$$$48 from './sections/Product/ImageGallerySlider.tsx'
import * as $$$$$$49 from './sections/Product/NotFound.tsx'
import * as $$$$$$50 from './sections/Product/NotFoundChallenge.tsx'
import * as $$$$$$51 from './sections/Product/ProductInfo.tsx'
import * as $$$$$$52 from './sections/Product/ProductMain.tsx'
import * as $$$$$$53 from './sections/Product/ProductMainNew.tsx'
import * as $$$$$$54 from './sections/Product/ProductShelf.tsx'
import * as $$$$$$55 from './sections/Product/ProductShelfWithImage.tsx'
import * as $$$$$$56 from './sections/Product/SearchResult.tsx'
import * as $$$$$$57 from './sections/Product/SubscriptionModal.tsx'
import * as $$$$$$58 from './sections/Product/Trustvox.tsx'
import * as $$$$$$59 from './sections/Product/Wishlist.tsx'
import * as $$$$$$60 from './sections/Theme/Theme.tsx'

const manifest = {
	'loaders': {
		'site/loaders/availableIcons.ts': $$$2,
		'site/loaders/centralNavigation.ts': $$$3,
		'site/loaders/CustomPLPTitle.ts': $$$0,
		'site/loaders/PLPSectionsSEO.ts': $$$1,
		'site/loaders/seals.tsx': $$$4,
	},
	'sections': {
		'site/sections/Category/CategoryBanner.tsx': $$$$$$0,
		'site/sections/Category/CategoryCarousel.tsx': $$$$$$1,
		'site/sections/Category/CategoryGrid.tsx': $$$$$$2,
		'site/sections/Category/CategoryGridCircle.tsx': $$$$$$3,
		'site/sections/Category/CategoryList.tsx': $$$$$$4,
		'site/sections/Content/Benefits.tsx': $$$$$$5,
		'site/sections/Content/BlogPosts.tsx': $$$$$$6,
		'site/sections/Content/CallToAction.tsx': $$$$$$7,
		'site/sections/Content/CardsSlider.tsx': $$$$$$8,
		'site/sections/Content/CardsWithCta.tsx': $$$$$$9,
		'site/sections/Content/CardsWithImageCta.tsx': $$$$$$10,
		'site/sections/Content/DescriptionWithCta.tsx': $$$$$$11,
		'site/sections/Content/Faq.tsx': $$$$$$12,
		'site/sections/Content/Features.tsx': $$$$$$13,
		'site/sections/Content/Hero.tsx': $$$$$$14,
		'site/sections/Content/HighlightsBanner.tsx': $$$$$$15,
		'site/sections/Content/ImageSection.tsx': $$$$$$16,
		'site/sections/Content/Logos.tsx': $$$$$$17,
		'site/sections/Content/RenderHTMLBlock.tsx': $$$$$$18,
		'site/sections/Content/RichText.tsx': $$$$$$19,
		'site/sections/Content/TextAndBanner.tsx': $$$$$$20,
		'site/sections/Content/VideoModal.tsx': $$$$$$21,
		'site/sections/Footer/Footer.tsx': $$$$$$22,
		'site/sections/Gallery.tsx': $$$$$$23,
		'site/sections/Header/Header.tsx': $$$$$$24,
		'site/sections/Images/AccordionWithImages.tsx': $$$$$$25,
		'site/sections/Images/BannerImage.tsx': $$$$$$26,
		'site/sections/Images/BannerInfo.tsx': $$$$$$27,
		'site/sections/Images/BannerInfoContainer.tsx': $$$$$$28,
		'site/sections/Images/BannerInfoVideo.tsx': $$$$$$29,
		'site/sections/Images/BannerInfoWithDivider.tsx': $$$$$$30,
		'site/sections/Images/BannerInfoWithItems.tsx': $$$$$$31,
		'site/sections/Images/Carousel.tsx': $$$$$$32,
		'site/sections/Images/ImageGallery.tsx': $$$$$$33,
		'site/sections/Images/ImageGrid.tsx': $$$$$$34,
		'site/sections/Images/ShoppableBanner.tsx': $$$$$$35,
		'site/sections/Insider/InsiderTracking.tsx': $$$$$$36,
		'site/sections/Insider/OrderTracking.tsx': $$$$$$37,
		'site/sections/Insider/types.ts': $$$$$$38,
		'site/sections/Links/Shortcuts.tsx': $$$$$$39,
		'site/sections/Miscellaneous/CampaignTimer.tsx': $$$$$$40,
		'site/sections/Miscellaneous/CookieConsent.tsx': $$$$$$41,
		'site/sections/Miscellaneous/FloatingButtons.tsx': $$$$$$42,
		'site/sections/Miscellaneous/Slide.tsx': $$$$$$43,
		'site/sections/Miscellaneous/Space.tsx': $$$$$$44,
		'site/sections/Newsletter/Newsletter.tsx': $$$$$$45,
		'site/sections/Product/Description.tsx': $$$$$$46,
		'site/sections/Product/ImageGalleryFrontBack.tsx': $$$$$$47,
		'site/sections/Product/ImageGallerySlider.tsx': $$$$$$48,
		'site/sections/Product/NotFound.tsx': $$$$$$49,
		'site/sections/Product/NotFoundChallenge.tsx': $$$$$$50,
		'site/sections/Product/ProductInfo.tsx': $$$$$$51,
		'site/sections/Product/ProductMain.tsx': $$$$$$52,
		'site/sections/Product/ProductMainNew.tsx': $$$$$$53,
		'site/sections/Product/ProductShelf.tsx': $$$$$$54,
		'site/sections/Product/ProductShelfWithImage.tsx': $$$$$$55,
		'site/sections/Product/SearchResult.tsx': $$$$$$56,
		'site/sections/Product/SubscriptionModal.tsx': $$$$$$57,
		'site/sections/Product/Trustvox.tsx': $$$$$$58,
		'site/sections/Product/Wishlist.tsx': $$$$$$59,
		'site/sections/Theme/Theme.tsx': $$$$$$60,
	},
	'matchers': {
		'site/matchers/canonical.ts': $$$$$$$0,
	},
	'apps': {
		'site/apps/decohub.ts': $$$$$$$$$$$0,
		'site/apps/site.ts': $$$$$$$$$$$1,
	},
	'name': 'site',
	'baseUrl': import.meta.url,
}

export type Manifest = typeof manifest

export default manifest
