// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from './apps/decohub.ts'
import * as $$$$$$$$$$$1 from './apps/site.ts'
import * as $$$2 from './loaders/availableIcons.ts'
import * as $$$3 from './loaders/centralNavigation.ts'
import * as $$$0 from './loaders/CustomPLPTitle.ts'
import * as $$$1 from './loaders/PLPSectionsSEO.ts'
import * as $$$4 from './loaders/seals.tsx'
import * as $$$$$$$0 from './matchers/canonical.ts'
import * as $$$$$$0 from './sections/Analytics/Purchase.tsx'
import * as $$$$$$1 from './sections/Animation/Animation.tsx'
import * as $$$$$$2 from './sections/Category/CategoryBanner.tsx'
import * as $$$$$$3 from './sections/Category/CategoryCarousel.tsx'
import * as $$$$$$4 from './sections/Category/CategoryGrid.tsx'
import * as $$$$$$5 from './sections/Category/CategoryGridCircle.tsx'
import * as $$$$$$6 from './sections/Category/CategoryList.tsx'
import * as $$$$$$7 from './sections/CategoryDescription/CategoryInfoCard.tsx'
import * as $$$$$$8 from './sections/CategoryDescription/CategoryOnlyText.tsx'
import * as $$$$$$10 from './sections/CentralAtendimento/BannerCabecalho.tsx'
import * as $$$$$$9 from './sections/CentralAtendimento/BannerCTA.tsx'
import * as $$$$$$11 from './sections/CentralAtendimento/CardEmail.tsx'
import * as $$$$$$12 from './sections/CentralAtendimento/CardEmailLinked.tsx'
import * as $$$$$$13 from './sections/CentralAtendimento/CardNumbered.tsx'
import * as $$$$$$14 from './sections/CentralAtendimento/CardNumberedSection.tsx'
import * as $$$$$$15 from './sections/CentralAtendimento/CardPhone.tsx'
import * as $$$$$$16 from './sections/CentralAtendimento/CardRichText.tsx'
import * as $$$$$$17 from './sections/CentralAtendimento/CardsTitle.tsx'
import * as $$$$$$18 from './sections/CentralAtendimento/CardsTitleSimple.tsx'
import * as $$$$$$19 from './sections/CentralAtendimento/CardsTitleSimpleH3.tsx'
import * as $$$$$$20 from './sections/CentralAtendimento/EmptySection.tsx'
import * as $$$$$$21 from './sections/CentralAtendimento/Faq.tsx'
import * as $$$$$$22 from './sections/CentralAtendimento/FormCard.tsx'
import * as $$$$$$23 from './sections/CentralAtendimento/InfoCard.tsx'
import * as $$$$$$24 from './sections/CentralAtendimento/InfoCardSection.tsx'
import * as $$$$$$25 from './sections/CentralAtendimento/InfoCardSectionPromotion.tsx'
import * as $$$$$$26 from './sections/CentralAtendimento/NavegacaoCentralAtendimento.tsx'
import * as $$$$$$27 from './sections/CentralAtendimento/NavigationMenu.tsx'
import * as $$$$$$28 from './sections/CentralAtendimento/NavigationPage.tsx'
import * as $$$$$$29 from './sections/CentralAtendimento/PromotionsSection.tsx'
import * as $$$$$$30 from './sections/CentralAtendimento/TextInput.tsx'
import * as $$$$$$31 from './sections/Content/Benefits.tsx'
import * as $$$$$$32 from './sections/Content/BlogPosts.tsx'
import * as $$$$$$33 from './sections/Content/CallToAction.tsx'
import * as $$$$$$34 from './sections/Content/CardsSlider.tsx'
import * as $$$$$$35 from './sections/Content/CardsWithCta.tsx'
import * as $$$$$$36 from './sections/Content/CardsWithImageCta.tsx'
import * as $$$$$$37 from './sections/Content/CouponPopup.tsx'
import * as $$$$$$38 from './sections/Content/DescriptionWithCta.tsx'
import * as $$$$$$39 from './sections/Content/Faq.tsx'
import * as $$$$$$40 from './sections/Content/Features.tsx'
import * as $$$$$$41 from './sections/Content/FormLojistas.tsx'
import * as $$$$$$42 from './sections/Content/FormProfissionais.tsx'
import * as $$$$$$43 from './sections/Content/FormPromoLeeds.tsx'
import * as $$$$$$44 from './sections/Content/FormPromoLeeds2.tsx'
import * as $$$$$$45 from './sections/Content/Hero.tsx'
import * as $$$$$$46 from './sections/Content/HighlightsBanner.tsx'
import * as $$$$$$47 from './sections/Content/ImageSection.tsx'
import * as $$$$$$48 from './sections/Content/InfluencersCarousel.tsx'
import * as $$$$$$49 from './sections/Content/Logos.tsx'
import * as $$$$$$50 from './sections/Content/PageMagnesioCustomerFinish.tsx'
import * as $$$$$$51 from './sections/Content/PageProfessionalsHealth.tsx'
import * as $$$$$$52 from './sections/Content/PopupPromoEbookLeeds.tsx'
import * as $$$$$$53 from './sections/Content/RenderHTMLBlock.tsx'
import * as $$$$$$54 from './sections/Content/RichText.tsx'
import * as $$$$$$55 from './sections/Content/SeoCustom.tsx'
import * as $$$$$$56 from './sections/Content/SubscriptionPopup.tsx'
import * as $$$$$$57 from './sections/Content/Table.tsx'
import * as $$$$$$58 from './sections/Content/Testimonials.tsx'
import * as $$$$$$59 from './sections/Content/TextAndBanner.tsx'
import * as $$$$$$60 from './sections/Content/Timeline.tsx'
import * as $$$$$$61 from './sections/Content/VideoModal.tsx'
import * as $$$$$$62 from './sections/Footer/Footer.tsx'
import * as $$$$$$63 from './sections/Gallery.tsx'
import * as $$$$$$64 from './sections/Header/Header.tsx'
import * as $$$$$$65 from './sections/Images/AccordionWithImages.tsx'
import * as $$$$$$66 from './sections/Images/BannerImage.tsx'
import * as $$$$$$67 from './sections/Images/BannerInfo.tsx'
import * as $$$$$$68 from './sections/Images/BannerInfoContainer.tsx'
import * as $$$$$$69 from './sections/Images/BannerInfoVideo.tsx'
import * as $$$$$$70 from './sections/Images/BannerInfoWithDivider.tsx'
import * as $$$$$$71 from './sections/Images/BannerInfoWithItems.tsx'
import * as $$$$$$72 from './sections/Images/Carousel.tsx'
import * as $$$$$$73 from './sections/Images/ImageGallery.tsx'
import * as $$$$$$74 from './sections/Images/ImageGrid.tsx'
import * as $$$$$$75 from './sections/Images/ShoppableBanner.tsx'
import * as $$$$$$76 from './sections/Insider/InsiderTracking.tsx'
import * as $$$$$$77 from './sections/Insider/OrderTracking.tsx'
import * as $$$$$$78 from './sections/Insider/types.ts'
import * as $$$$$$79 from './sections/Links/Shortcuts.tsx'
import * as $$$$$$80 from './sections/Miscellaneous/CampaignTimer.tsx'
import * as $$$$$$81 from './sections/Miscellaneous/CookieConsent.tsx'
import * as $$$$$$82 from './sections/Miscellaneous/FloatingButtons.tsx'
import * as $$$$$$83 from './sections/Miscellaneous/Slide.tsx'
import * as $$$$$$84 from './sections/Miscellaneous/Space.tsx'
import * as $$$$$$85 from './sections/Newsletter/Newsletter.tsx'
import * as $$$$$$86 from './sections/Product/Description.tsx'
import * as $$$$$$87 from './sections/Product/ImageGalleryFrontBack.tsx'
import * as $$$$$$88 from './sections/Product/ImageGallerySlider.tsx'
import * as $$$$$$89 from './sections/Product/NotFound.tsx'
import * as $$$$$$90 from './sections/Product/NotFoundChallenge.tsx'
import * as $$$$$$91 from './sections/Product/ProductInfo.tsx'
import * as $$$$$$92 from './sections/Product/ProductMain.tsx'
import * as $$$$$$93 from './sections/Product/ProductMainNew.tsx'
import * as $$$$$$94 from './sections/Product/ProductShelf.tsx'
import * as $$$$$$95 from './sections/Product/ProductShelfWithImage.tsx'
import * as $$$$$$96 from './sections/Product/SearchResult.tsx'
import * as $$$$$$97 from './sections/Product/SubscriptionModal.tsx'
import * as $$$$$$98 from './sections/Product/Trustvox.tsx'
import * as $$$$$$99 from './sections/Product/Wishlist.tsx'
import * as $$$$$$100 from './sections/ProductDescription/DescriptionNew.tsx'
import * as $$$$$$101 from './sections/ProductDescription/ProductBenefits.tsx'
import * as $$$$$$102 from './sections/ProductDescription/ProductComparison.tsx'
import * as $$$$$$103 from './sections/ProductDescription/ProductContainer.tsx'
import * as $$$$$$104 from './sections/ProductDescription/ProductGallery.tsx'
import * as $$$$$$105 from './sections/ProductDescription/ProductInfoCard.tsx'
import * as $$$$$$106 from './sections/ProductDescription/ProductInfoCard1WithBackground.tsx'
import * as $$$$$$107 from './sections/ProductDescription/ProductNutritionalHighlights.tsx'
import * as $$$$$$108 from './sections/ProductDescription/ProductNutritionalTable.tsx'
import * as $$$$$$109 from './sections/ProductDescription/ProductNutritionalTable2.tsx'
import * as $$$$$$110 from './sections/ProductDescription/ProductSpace.tsx'
import * as $$$$$$111 from './sections/Search/SeoPLPMiddleware.tsx'
import * as $$$$$$112 from './sections/Social/WhatsApp.tsx'
import * as $$$$$$113 from './sections/Social/WhatsAppFlutuante.tsx'
import * as $$$$$$114 from './sections/Theme/Theme.tsx'

const manifest = {
	'loaders': {
		'site/loaders/availableIcons.ts': $$$2,
		'site/loaders/centralNavigation.ts': $$$3,
		'site/loaders/CustomPLPTitle.ts': $$$0,
		'site/loaders/PLPSectionsSEO.ts': $$$1,
		'site/loaders/seals.tsx': $$$4,
	},
	'sections': {
		'site/sections/Analytics/Purchase.tsx': $$$$$$0,
		'site/sections/Animation/Animation.tsx': $$$$$$1,
		'site/sections/Category/CategoryBanner.tsx': $$$$$$2,
		'site/sections/Category/CategoryCarousel.tsx': $$$$$$3,
		'site/sections/Category/CategoryGrid.tsx': $$$$$$4,
		'site/sections/Category/CategoryGridCircle.tsx': $$$$$$5,
		'site/sections/Category/CategoryList.tsx': $$$$$$6,
		'site/sections/CategoryDescription/CategoryInfoCard.tsx': $$$$$$7,
		'site/sections/CategoryDescription/CategoryOnlyText.tsx': $$$$$$8,
		'site/sections/CentralAtendimento/BannerCabecalho.tsx': $$$$$$10,
		'site/sections/CentralAtendimento/BannerCTA.tsx': $$$$$$9,
		'site/sections/CentralAtendimento/CardEmail.tsx': $$$$$$11,
		'site/sections/CentralAtendimento/CardEmailLinked.tsx': $$$$$$12,
		'site/sections/CentralAtendimento/CardNumbered.tsx': $$$$$$13,
		'site/sections/CentralAtendimento/CardNumberedSection.tsx': $$$$$$14,
		'site/sections/CentralAtendimento/CardPhone.tsx': $$$$$$15,
		'site/sections/CentralAtendimento/CardRichText.tsx': $$$$$$16,
		'site/sections/CentralAtendimento/CardsTitle.tsx': $$$$$$17,
		'site/sections/CentralAtendimento/CardsTitleSimple.tsx': $$$$$$18,
		'site/sections/CentralAtendimento/CardsTitleSimpleH3.tsx': $$$$$$19,
		'site/sections/CentralAtendimento/EmptySection.tsx': $$$$$$20,
		'site/sections/CentralAtendimento/Faq.tsx': $$$$$$21,
		'site/sections/CentralAtendimento/FormCard.tsx': $$$$$$22,
		'site/sections/CentralAtendimento/InfoCard.tsx': $$$$$$23,
		'site/sections/CentralAtendimento/InfoCardSection.tsx': $$$$$$24,
		'site/sections/CentralAtendimento/InfoCardSectionPromotion.tsx': $$$$$$25,
		'site/sections/CentralAtendimento/NavegacaoCentralAtendimento.tsx': $$$$$$26,
		'site/sections/CentralAtendimento/NavigationMenu.tsx': $$$$$$27,
		'site/sections/CentralAtendimento/NavigationPage.tsx': $$$$$$28,
		'site/sections/CentralAtendimento/PromotionsSection.tsx': $$$$$$29,
		'site/sections/CentralAtendimento/TextInput.tsx': $$$$$$30,
		'site/sections/Content/Benefits.tsx': $$$$$$31,
		'site/sections/Content/BlogPosts.tsx': $$$$$$32,
		'site/sections/Content/CallToAction.tsx': $$$$$$33,
		'site/sections/Content/CardsSlider.tsx': $$$$$$34,
		'site/sections/Content/CardsWithCta.tsx': $$$$$$35,
		'site/sections/Content/CardsWithImageCta.tsx': $$$$$$36,
		'site/sections/Content/CouponPopup.tsx': $$$$$$37,
		'site/sections/Content/DescriptionWithCta.tsx': $$$$$$38,
		'site/sections/Content/Faq.tsx': $$$$$$39,
		'site/sections/Content/Features.tsx': $$$$$$40,
		'site/sections/Content/FormLojistas.tsx': $$$$$$41,
		'site/sections/Content/FormProfissionais.tsx': $$$$$$42,
		'site/sections/Content/FormPromoLeeds.tsx': $$$$$$43,
		'site/sections/Content/FormPromoLeeds2.tsx': $$$$$$44,
		'site/sections/Content/Hero.tsx': $$$$$$45,
		'site/sections/Content/HighlightsBanner.tsx': $$$$$$46,
		'site/sections/Content/ImageSection.tsx': $$$$$$47,
		'site/sections/Content/InfluencersCarousel.tsx': $$$$$$48,
		'site/sections/Content/Logos.tsx': $$$$$$49,
		'site/sections/Content/PageMagnesioCustomerFinish.tsx': $$$$$$50,
		'site/sections/Content/PageProfessionalsHealth.tsx': $$$$$$51,
		'site/sections/Content/PopupPromoEbookLeeds.tsx': $$$$$$52,
		'site/sections/Content/RenderHTMLBlock.tsx': $$$$$$53,
		'site/sections/Content/RichText.tsx': $$$$$$54,
		'site/sections/Content/SeoCustom.tsx': $$$$$$55,
		'site/sections/Content/SubscriptionPopup.tsx': $$$$$$56,
		'site/sections/Content/Table.tsx': $$$$$$57,
		'site/sections/Content/Testimonials.tsx': $$$$$$58,
		'site/sections/Content/TextAndBanner.tsx': $$$$$$59,
		'site/sections/Content/Timeline.tsx': $$$$$$60,
		'site/sections/Content/VideoModal.tsx': $$$$$$61,
		'site/sections/Footer/Footer.tsx': $$$$$$62,
		'site/sections/Gallery.tsx': $$$$$$63,
		'site/sections/Header/Header.tsx': $$$$$$64,
		'site/sections/Images/AccordionWithImages.tsx': $$$$$$65,
		'site/sections/Images/BannerImage.tsx': $$$$$$66,
		'site/sections/Images/BannerInfo.tsx': $$$$$$67,
		'site/sections/Images/BannerInfoContainer.tsx': $$$$$$68,
		'site/sections/Images/BannerInfoVideo.tsx': $$$$$$69,
		'site/sections/Images/BannerInfoWithDivider.tsx': $$$$$$70,
		'site/sections/Images/BannerInfoWithItems.tsx': $$$$$$71,
		'site/sections/Images/Carousel.tsx': $$$$$$72,
		'site/sections/Images/ImageGallery.tsx': $$$$$$73,
		'site/sections/Images/ImageGrid.tsx': $$$$$$74,
		'site/sections/Images/ShoppableBanner.tsx': $$$$$$75,
		'site/sections/Insider/InsiderTracking.tsx': $$$$$$76,
		'site/sections/Insider/OrderTracking.tsx': $$$$$$77,
		'site/sections/Insider/types.ts': $$$$$$78,
		'site/sections/Links/Shortcuts.tsx': $$$$$$79,
		'site/sections/Miscellaneous/CampaignTimer.tsx': $$$$$$80,
		'site/sections/Miscellaneous/CookieConsent.tsx': $$$$$$81,
		'site/sections/Miscellaneous/FloatingButtons.tsx': $$$$$$82,
		'site/sections/Miscellaneous/Slide.tsx': $$$$$$83,
		'site/sections/Miscellaneous/Space.tsx': $$$$$$84,
		'site/sections/Newsletter/Newsletter.tsx': $$$$$$85,
		'site/sections/Product/Description.tsx': $$$$$$86,
		'site/sections/Product/ImageGalleryFrontBack.tsx': $$$$$$87,
		'site/sections/Product/ImageGallerySlider.tsx': $$$$$$88,
		'site/sections/Product/NotFound.tsx': $$$$$$89,
		'site/sections/Product/NotFoundChallenge.tsx': $$$$$$90,
		'site/sections/Product/ProductInfo.tsx': $$$$$$91,
		'site/sections/Product/ProductMain.tsx': $$$$$$92,
		'site/sections/Product/ProductMainNew.tsx': $$$$$$93,
		'site/sections/Product/ProductShelf.tsx': $$$$$$94,
		'site/sections/Product/ProductShelfWithImage.tsx': $$$$$$95,
		'site/sections/Product/SearchResult.tsx': $$$$$$96,
		'site/sections/Product/SubscriptionModal.tsx': $$$$$$97,
		'site/sections/Product/Trustvox.tsx': $$$$$$98,
		'site/sections/Product/Wishlist.tsx': $$$$$$99,
		'site/sections/ProductDescription/DescriptionNew.tsx': $$$$$$100,
		'site/sections/ProductDescription/ProductBenefits.tsx': $$$$$$101,
		'site/sections/ProductDescription/ProductComparison.tsx': $$$$$$102,
		'site/sections/ProductDescription/ProductContainer.tsx': $$$$$$103,
		'site/sections/ProductDescription/ProductGallery.tsx': $$$$$$104,
		'site/sections/ProductDescription/ProductInfoCard.tsx': $$$$$$105,
		'site/sections/ProductDescription/ProductInfoCard1WithBackground.tsx': $$$$$$106,
		'site/sections/ProductDescription/ProductNutritionalHighlights.tsx': $$$$$$107,
		'site/sections/ProductDescription/ProductNutritionalTable.tsx': $$$$$$108,
		'site/sections/ProductDescription/ProductNutritionalTable2.tsx': $$$$$$109,
		'site/sections/ProductDescription/ProductSpace.tsx': $$$$$$110,
		'site/sections/Search/SeoPLPMiddleware.tsx': $$$$$$111,
		'site/sections/Social/WhatsApp.tsx': $$$$$$112,
		'site/sections/Social/WhatsAppFlutuante.tsx': $$$$$$113,
		'site/sections/Theme/Theme.tsx': $$$$$$114,
	},
	'matchers': {
		'site/matchers/canonical.ts': $$$$$$$0,
	},
	'apps': {
		'site/apps/decohub.ts': $$$$$$$$$$$0,
		'site/apps/site.ts': $$$$$$$$$$$1,
	},
	'name': 'site',
	'baseUrl': import.meta.url,
}

export type Manifest = typeof manifest

export default manifest
